version: '3'

services:
  testcluster_node:
    image: skynetnode_img:v1
    build:
      context: ./skynetnode
      dockerfile: Dockerfile.web
    container_name: testcluster_node
    tty: true
    hostname: game-server
    command: /bin/bash -c "cd /work/publish && ./run start all && tail -f /dev/null"
    volumes:
      - ~/testcluster:/work:rw
    networks:
      testcluster:
        aliases:
          - testcluster_node

  testcluster_mysql:
    image: mysql:5.7
    container_name: testcluster_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "163.com"
    volumes:
      - ~/testcluster/data/mysql:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime
    networks:
      testcluster:
        aliases:
          - testcluster_mysql

networks:
  testcluster:
